# Menu
menu:
  主页: /
  相册: /gallery
  归档: /archives
  关于: /about
rss: /atom.xml

# Miscellaneous
favicon: /favicon.ico
brand: /images/logo.svg

# Ocean 主页视频
# 多种格式的视频用于支持不同的浏览器，这里只需要配置好路径，前提是我把视频相关文件统一目录存放。
ocean:
  overlay: true      # 可选，false 则 Ocean 视频下方的笔触式遮盖不显示
  path: /images/ocean/      # 视频统一存放路径，格式 mp4/ogg/webm
  brand: /images/logo.svg      # 可选，一个小 Logo

# 内容
excerpt_link: 阅读全文...
excerpt_all: false

# fancybox
fancybox: true

# Toc
toc: true

mathjax:
  enable: true
  cdn: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Plugin Live2d
live2d:
  model:
    use: live2d-widget-model-tororo
  display:
    superSample: 2
    width: 180
    height: 360
    position: left
    hOffset: 20
    vOffset: -60
  mobile:
    show: false
  react:
    opacityDefault: 0.7
    opacityOnHover: 0.2

# Gitalk
gitalk:
  enable: true      # 是否启用，默认：false（关闭），true（启用）
  clientID: '00602273bcb44baec0a4'     # 申请 GitHub Application 网页上对应的 Client ID 与 Client Secret 参数
  clientSecret: '532c033a72eb4b94cf1e9aebdb0a9857fdedfe80'     # 同上
  repo: 'xiangfa.org'     # 创建的仓库名称
  owner: 'amery2010'      # Github ID
  admin: ['amery2010']     # Github ID

# Valine
valine:
  enable: false      # 是否启用，默认：false（关闭），true（启用）
  el: 'vcomments'      # Valine 的初始化挂载器，无需更改
  appId:       # 从 LeanCloud 的应用中得到的 appId
  appKey:       # 从 LeanCloud 的应用中得到的APP Key
  notify: false      # 评论回复邮件提醒，默认：false（关闭），true（启用）
  verify: true      # 验证码，为避免过多的垃圾评论，所以默认 true（启用），false（关闭）
  avatar: 'mp'      # Gravatar 头像展示方式
  pageSize: '10'      # 评论列表分页，每页条数
  placeholder: '请输入...'      # 评论框占位提示符